courseRegistrationSystem/config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :students, :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'students/index'
  get 'students/all_courses'
  get 'students/registered_courses'
  get 'students/semister'
  get 'students/semister_r'
  get 'students/semister_result/:id' => "students#semister_result"
  get 'students/semister_courses/:id' => "students#semister_courses"
  get 'students/register_course' => "students#register_course"

  get 'students/search'
  get 'students/search_result' => "students#search_result"

  root to: "students#semister"
end

courseRegistrationSystem/app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

courseRegistrationSystem/app/models/course.rb
class Course < ApplicationRecord

  has_many :student_course_registers

  belongs_to :semister

  def decorate
    @decorate ||=CourseDecorator.new self
  end

end

courseRegistrationSystem/app/models/semister.rb
class Semister < ApplicationRecord
  has_many :courses, dependent: :destroy
end

courseRegistrationSystem/app/models/student.rb
class Student < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
   mount_uploader :avatar, AvatarUploader # Tells rails to use this uploader for this model.
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :student_course_registers

  #getter
  def full_name
    [first_name,last_name].join(' ')
  end

  #setter
  def full_name=(name)
    split = name.split(' ',2)
    first_name=split.first
    last_name=split.last
  end

  def image_path
    @path="/uploads/student/avatar/1/logo.jpg"
  end

end

courseRegistrationSystem/app/models/student_course_register.rb
class StudentCourseRegister < ApplicationRecord
  belongs_to :student ,foreign_key: "student_id"
  belongs_to :course ,foreign_key: "course_id"
  validates :gpa, presence: true, :inclusion => 0..4

end

courseRegistrationSystem/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action  :authenticate_student!


end

courseRegistrationSystem/app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

private
  def sign_up_params
    params.require(:student).permit(:first_name, :last_name,:avatar ,:email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:student).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end
end

courseRegistrationSystem/app/controllers/students_controller.rb
class StudentsController < ApplicationController



  def index
    @student_name="My name is akash"
  end

  def all_courses
    @student_id=current_student.id
    @presenter=Students::AllCoursesPresenter.new(@student_id)
  end

  def registered_courses
    @student_id=current_student.id
    @presenter=Students::RegisteredCoursesPresenter.new(@student_id)
  end

  def semister
    @presenter=Students::SemisterPresenter.new
  end

  def semister_courses
    @student_id=current_student.id
    @semister_id=params["id"]
    @presenter=Students::SemisterCoursesPresenter.new(@semister_id,@student_id)
  end

  def register_course
    @id=params[:id]
    if @id.nil?
      render json: []

    end
    @student_id=current_student.id
    @register=StudentCourseRegister.new( :student_id=> @student_id ,:course_id=>@id)

    @register.save(validate: false)

    render json: @register

  end


  def semister_r
    @presenter=Students::SemisterPresenter.new

  end

  def semister_result
    @student_id=current_student.id
    @semister_id=params[:id]
    @presenter=Students::SemisterResultPresenter.new(@student_id ,@semister_id)

  end


  def search

  end

  def search_result
    @student_id=current_student.id
    @search_by=params[:search_by]
    @search_string=params[:search_string]
    @presenter=Students::SearchResultPresenter.new( @student_id, @search_by, @search_string)

    render json: @presenter.result, :include =>[:course]


  end


end

courseRegistrationSystem/app/helpers/registrations_helper.rb
module RegistrationsHelper
end

courseRegistrationSystem/app/helpers/students_helper.rb
module StudentsHelper
end

courseRegistrationSystem/app/views/layouts/_footer.html.erb
<div class="panel-footer navbar-bottom">
  Developed by <a href="http://akash365.com" target="_blank">syed mhamudul hasan</a>
</div>

courseRegistrationSystem/app/views/layouts/_navbar.html.erb
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="../">

        <!-- <img src= " <%= asset_path "mylogo.jpg" %>" alt="no image">-->
      </a>
      <a class="navbar-brand" href="/">Course Management System</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-left">
        <li><a href="/students/all_courses">AllCourses</a></li>
        <li><a href="/students/registered_courses">RegisteredCourse</a></li>
        <li><a href="/students/semister">Semister</a></li>
        <li><a href="/students/semister_r">SemisterResult</a> </li>
        <li><a href="/students/search">Search</a> </li>
      </ul>
    </div>
  </div>
</div>
<ul class="nav navbar-nav navbar-right">
  <% if student_signed_in? %>

      <% if current_student.is_admin? %>
          <li>
      <a href="/admin">Admin Pannel</a>
          <% end%>
      </li>
      <li>
        <img src=" <%= current_student.image_path%>" alt="bno image" style="height: 50px;width: 50px">
      </li>
      <li>
        <%= link_to current_student.email, edit_student_registration_path %>
      </li>
      <li>
        <%= link_to "Logout", destroy_student_session_path , :method => :delete %>
      </li>
  <% else %>
      <li>
        <%= link_to "Sign Up", new_student_registration_path %>
      </li>
      <li>
        <%= link_to "Login", new_student_session_path %>
      </li>
  <% end %>
</ul>

courseRegistrationSystem/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dashboard Starter UI, by Keen IO</title>
  <meta name='viewport' content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no' />
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <style>
    body{
      font-size: 16px;
      line-height: 1.2;
    }
  </style>

  <script>
    //for dummy registration
    $(function () {

    })
  </script>
</head>
<body class="application">

<%= render "/layouts/navbar" %>

<div class="container-fluid">
  <div class="container">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

  </div>
  <br/>

  <div class="row">

      <%= yield %>
  </div>

  <br>
  <%= render "/layouts/footer" %>

</div>
</body>
</html>

courseRegistrationSystem/app/views/students/all_courses.html.erb
<div class="container">



<p id="notice"><%= notice %></p>

<h1>Couses</h1>

<table class="table table-bordered">
  <thead>
  <tr>
    <th>Name</th>
    <th>SemisterName</th>

  </tr>
  </thead>

  <tbody>
  <% @presenter.taken_courses.each do |course| %>
      <tr>
        <td><%= course.name %></td>
        <td><%= course.decorate.semister_name %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>
</div>

courseRegistrationSystem/app/views/students/index.html.erb
<div class="col-lg-12">

<div class="col-lg-2">
 <%= truncate(@student_name , length: 5)%>
</div>
</div>

courseRegistrationSystem/app/views/students/registered_courses.html.erb
<div class="container">



<p id="notice"><%= notice %></p>

<h1 class="well">Registed course</h1>

  <% if @presenter.registered_courses.any? == true %>
      <table class="table table-bordered">
        <thead>
        <tr>
          <th>RegisterCourseName</th>
          <th>Semister Name</th>

        </tr>
        </thead>

        <tbody>
        <% @presenter.registered_courses.each do |course| %>
            <tr>
              <td><%= course.name %></td>
              <td><%= course.decorate.semister_name  %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
  <% end %>

  <% if @presenter.registered_courses.any? == false %>
      <div class="alert alert-danger">
        You have no registered course
      </div>
  <% end %>




<br>
</div>

courseRegistrationSystem/app/views/students/search.html.erb
<div class="container">
  <h2>Select serach criteria</h2>
  <form>
    <div class="form-group">
      <label for="sel1">Select list (select one):</label>
      <select class="form-control" id="sel1">
        <option value="1">SemisterName</option>
        <option value="2">CourseName</option>

      </select>
      <br>
      <label for="sel2">Input search string</label>
      <input class="form-control" type="text" value="test" id="search_string">
      <br>
      <input type="button" value="search" id="search">
    </div>
  </form>

  <div class="row">
    <table class="table table-bordered" id="tbl">
      <thead>
      <tr>
      <th>
        CourseName
      </th>
        <th>
          GPA
        </th>
      </tr>
      </thead>
      <tbody>
      <tr>

      </tr>
      </tbody>
    </table>

  </div>
</div>

<script>
$('#search').on('click',function(){
  var search_by=$('#sel1').val();
  var search_string=$('#search_string').val();
  //alert(search_string);
  $("#tbl > tbody").html("");
  $.ajax({
    type: "GET",
    url: '/students/search_result', //sumbits it to the given url of the form
    data: { 'search_by' : search_by, 'search_string':search_string},
    dataType: "JSON",
    success:function(json){
      console.log(json);

      for(var i=0 ; i<json.length ;i++){
        var tr = '<tr>';
        tr = tr + '<td>' + json[i].course.name + '</td>';
        tr = tr + '<td>' + json[i].gpa + '</td>';
        tr = tr + '</tr>';


        $('#tbl > tbody:first').prepend(tr);
      }


    }
  });

})

</script>

courseRegistrationSystem/app/views/students/semister.html.erb
<div class="container">

<h2>
  Register  semister course here
</h2>
  <br>

  <% if @presenter.semisters.any? == true %>
      <table class="table table-bordered table-striped">
        <thead>
        <tr>
          <th>SemisterName</th>
          <th>Action</th>
        </tr>
        </thead>
        <tbody class="product-index">

        <% @presenter.semisters.each do |semister| %>
            <tr>
              <td><%= semister.name %></td>
              <td><a href="/students/semister_courses/<%= semister.id %>">Register course</a></td>
            </tr>
        <% end %>
        </tbody>
      </table>
  <% else %>
     <div class="alert alert-danger">
       No active semister found
     </div>
  <% end %>


</div>

courseRegistrationSystem/app/views/students/semister_courses.html.erb
<div class="container">
  <h1 class="well">Course of <span class="alert alert-info"><%=  @presenter.semister.name %></span>   </h1>
  <% if @presenter.semister_courses.any? == true %>
      <table class="table table-bordered table-striped">
        <thead>
        <tr>
          <th>Course name</th>
          <th>IsCourseTaken</th>
          <th>Action</th>
        </tr>
        </thead>
        <tbody class="product-index">
        <!--Redering partial here -->
        <% @presenter.semister_courses.each do |course| %>
            <tr>
              <td><%= course.name %></td>
              <td><%= course.decorate.is_course_taken(current_student.id) %></td>
              <% if course.decorate.is_course_taken(current_student.id) == false %>
                  <td>
                    <button class="btn btn-success" onclick="enroll(<%=course.id %>,this)">Enroll</button>
                  </td>
              <% end %>

            </tr>

        <% end %>
        </tbody>
      </table>

      <div>
        <a href="/students/registered_courses" class="btn btn-primary" >Submit</a>

      </div>
  <% end %>

  <% if @presenter.semister_courses.any? == false %>
      <div class="alert alert-danger">
        No course has been given to semister
      </div>
  <% end %>

</div>

<script>


  function enroll(id,element) {
    console.log(element);
    //$(element).attr('disable','disabled')
    element.style.display="none";
    element.parentElement.parentElement.style.background = "green";

    $.ajax({
      type: "GET",
      url: '/students/register_course', //sumbits it to the given url of the form
      data: { 'id' : id},
      dataType: "JSON",
      success:function(json){
        console.log("success", json);
      }
    });
  }

</script>

courseRegistrationSystem/app/views/students/semister_r.html.erb
<div class="container">

  <h2>
    Click the semister to view the result
  </h2>
  <br>

  <% if @presenter.semisters.any? == true %>
      <table class="table table-bordered table-striped">
        <thead>
        <tr>
          <th>SemisterName</th>
          <th>Action</th>
        </tr>
        </thead>
        <tbody class="product-index">

        <% @presenter.semisters.each do |semister| %>
            <tr>
              <td><%= semister.name %></td>
              <td><a href="/students/semister_result/<%= semister.id %>">View result</a></td>
            </tr>
        <% end %>
        </tbody>
      </table>

      <% else %>
      <div class="alert alert-danger">
        No active semister found
      </div>
  <% end %>



</div>

courseRegistrationSystem/app/views/students/semister_result.html.erb
<div class="container">



<% if @presenter.results.any?  %>

<table class="table table-bordered table-striped">
  <thead>
  <tr>
    <th>SemisterName</th>
    <th>CourseName</th>
    <th>StudentName</th>
    <th>GPA</th>
  </tr>
  </thead>
  <tbody class="product-index">

<% @presenter.results.each do |result| %>
    <tr>
      <td><%= @presenter.semister.name %></td>
      <td><%= result.course.name %></td>
      <td><%= result.student.full_name %></td>
      <td><%= result.gpa %></td>
    </tr>
<% end %>
  <tr>
    <td colspan="3">
      CGPA
    </td>
    <td>
      <%=  @presenter.results.sum(:gpa)/ @presenter.results.count %>
    </td>
  </tr>
  </tbody>
</table>
<% else %>
<div class="alert alert-danger">
  No result for this semister
</div>
<% end %>


</div>