FcmService/config/routes.rb
Rails.application.routes.draw do
  resources :menu_items
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'resumes/index'

  get 'resumes/new'

  get 'resumes/create'

  get 'resumes/destroy'

  get 'home/index'
  post 's3file_upload/create'

  resources :resumes, only: [:index, :new, :create, :destroy]
  root "menu_items#index"

end

FcmService/app/models/album.rb
class Album < ActiveRecord::Base
  validates_presence_of :title
  validates :title, length: { minimum: 1, maximum: 100 }
end

FcmService/app/models/article.rb
class Article < ActiveRecord::Base
end

FcmService/app/models/author.rb
class Author < ActiveRecord::Base
  #first relationship
  has_many :articles
  #validation
  validates_presence_of :menu_item

  #Decorator logic
end

FcmService/app/models/fcm_android_messaging.rb
class FcmAndroidMessaging < ActiveRecord::Base
  after_save :do_foobar


  private
  def do_foobar

   @a=self.user_id
   @b='test'



  end
end

FcmService/app/models/menu_item.rb
class MenuItem < ActiveRecord::Base
  validates_presence_of :menu_item
end

FcmService/app/models/resume.rb
class Resume < ActiveRecord::Base
  mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
  validates :name, presence: true # Make sure the owner's name is present.
end

FcmService/app/models/s3file_upload.rb
class S3fileUpload < ActiveRecord::Base

  mount_uploader :avatar, AvatarUploader # Tells rails to use this uploader for this model.
end

FcmService/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  #global excetion handler
  rescue_from ::Exception ,with: :error_occurred

  protected

  def error_occurred(exception)

    error_details_json={error: exception.message ,
                        controller: params['controller'] ,
                        action: params['action'] ,
                        stacktrace: $ERROR_POSITION ,
                        source: $ERROR_INFO

    }.to_json

    if Rails.env.development?
      render json: error_details_json, status: 500
    else
      #Send mail by mailer
      @i=0
    end

    return
  end
end

FcmService/app/controllers/home_controller.rb
class HomeController < ApplicationController
  require 'android_messaging/fcm_registration_service'
  def index

    #from api
    @current_user_id=18
    @current_regiatration_token="abc"


    @fcm_registration = AndroidMessaging::FcmResgistationService.new(@current_user_id,@current_regiatration_token)

    @fcm_registration.SetOrUpdateFcmResgitrationToken







  end
end

FcmService/app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController
  before_action :set_menu_item, only: [:show, :edit, :update, :destroy]

  respond_to :html
  ###########################
  def new
    @menu_item = MenuItem.new
    respond_with(@menu_item)
  end

  def create
    @menu_item = MenuItem.new(menu_item_params)
    @menu_item.save
    respond_with(@menu_item)
  end
#########################################


  def index
    @menu_items = MenuItem.all
    respond_with(@menu_items)
  end

  def show
    respond_with(@menu_item)
  end



  def edit
  end



  def update
    @menu_item.update(menu_item_params)
    respond_with(@menu_item)
  end

  def destroy
    @menu_item.destroy
    respond_with(@menu_item)
  end

  private
    def set_menu_item
      @menu_item = MenuItem.find(params[:id])
    end

    def menu_item_params
      params.require(:menu_item).permit(:menu_item)
    end
end

FcmService/app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  def index
    @resumes = Resume.all
    #@exception=1/0
  end

  def new
    @resume = Resume.new
  end

  def create
    @resume = Resume.new(resume_params)

    if @resume.save
      redirect_to resumes_path, notice: "The resume #{@resume.name} has been uploaded."
    else
      render "new"
    end
  end

  def destroy
    @resume = Resume.find(params[:id])
    @resume.destroy
    redirect_to resumes_path, notice:  "The resume #{@resume.name} has been deleted."
  end

  private
  def resume_params
    params.require(:resume).permit(:name, :attachment)
  end
end

FcmService/app/controllers/s3file_upload_controller.rb
class S3fileUploadController < ApplicationController
  protect_from_forgery :except => [ :create]
  def index
    @s3file_upload=S3fileUpload.new

  end

  def create

    @file =:params[0]
    @i=0
  end
end

FcmService/app/helpers/home_helper.rb
module HomeHelper
end

FcmService/app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

FcmService/app/helpers/resumes_helper.rb
module ResumesHelper
end

FcmService/app/helpers/s3file_upload_helper.rb
module S3fileUploadHelper
end

FcmService/app/views/home/index.html.erb
<h1>Hello </h1>

FcmService/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FcmMessaging</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

FcmService/app/views/menu_items/_form.html.haml
= form_for @menu_item do |f|
  - if @menu_item.errors.any?
    #error_explanation
      %h2= "#{pluralize(@menu_item.errors.count, "error")} prohibited this menu_item from being saved:"
      %ul
        - @menu_item.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :menu_item
    = f.text_field :menu_item
  .actions
    = f.submit 'Save'

FcmService/app/views/menu_items/edit.html.haml
%h1 Editing menu_item

= render 'form'

= link_to 'Show', @menu_item
\|
= link_to 'Back', menu_items_path

FcmService/app/views/menu_items/index.html.haml
%h1 Listing menu_items

%table
  %thead
    %tr
      %th Menu item
      %th
      %th
      %th

  %tbody
    - @menu_items.each do |menu_item|
      %tr
        %td= menu_item.menu_item
        %td= link_to 'Show', menu_item
        %td= link_to 'Edit', edit_menu_item_path(menu_item)
        %td= link_to 'Destroy', menu_item, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Menu item', new_menu_item_path

FcmService/app/views/menu_items/new.html.haml
%h1 New menu_item

= render 'form'

= link_to 'Back', menu_items_path

FcmService/app/views/menu_items/show.html.haml
%p#notice= notice

%p
  %b Menu item:
  = @menu_item.menu_item

= link_to 'Edit', edit_menu_item_path(@menu_item)
\|
= link_to 'Back', menu_items_path

FcmService/app/views/resumes/create.html.erb
<h1>Resumes#create</h1>
<p>Find me in app/views/resumes/create.html.erb</p>

FcmService/app/views/resumes/destroy.html.erb
<h1>Resumes#destroy</h1>
<p>Find me in app/views/resumes/destroy.html.erb</p>

FcmService/app/views/resumes/index.html.erb
<% if !flash[:notice].blank? %>
    <div class="alert alert-info">
      <%= flash[:notice] %>
    </div>
<% end %>
<br />
<%= link_to "New Resume", new_resume_path, class: "btn btn-primary" %>
<br />
<br />
<table class="table table-bordered table-striped">
  <thead>
  <tr>
    <th>Name</th>
    <th>Download Link</th>
    <th>&nbsp;</th>
  </tr>
  </thead>
  <tbody>
  <% @resumes.each do |resume| %>
      <tr>
        <td><%= resume.name %></td>
        <td><%= link_to "Download Resume", resume.attachment_url %></td>
        <td><%= button_to "Delete",  resume, method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete #{resume.name}?" %></td>
      </tr>
  <% end %>
  </tbody>
</table>

FcmService/app/views/resumes/new.html.erb
<% if !@resume.errors.empty? %>
    <div class="alert alert-error">
      <ul>
        <% @resume.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

<div class="well">
  <%= form_for @resume, html: { multipart: true } do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.label :attachment %>
      <%= f.file_field :attachment %>
      <%= f.submit "Save", class: "btn btn-primary" %>
  <% end %>
</div>

FcmService/app/views/s3file_upload/index.html.erb
Hello s3 file upload

<form method="post" enctype="multipart/form-data" action="/s3file_upload/create" >
<input type="file" name="avatar" />

  <input type="submit" value="submit" />
</form>